sudo: false
language: node_js
node_js:
  - 4
  - 6
  - 10
matrix:
  fast_finish: true
env:
  global:
    - CXX=g++-4.8
script: npm run travis
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email: false
before_script:
  - npm prune
after_success:
  - npm install -g npx
  - npx -p node@8 npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
